import type { Metadata } from "next";
import 'primereact/resources/themes/lara-dark-blue/theme.css'
import '/node_modules/primeflex/primeflex.css'
import 'primeicons/primeicons.css';

import Navbar from './components/Navbar'
import Providers from "./components/system/Providers";
import ToastProvider from "./components/system/Toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='className'>
        <ToastProvider>
        <Providers>
          <Navbar />
          {children}
        </Providers>
        </ToastProvider>
      </body>
    </html>
  )
}
